# Generated by Django 4.2.28 on 2026-02-06 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arete', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('raza', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado_salud', models.CharField(choices=[('SANO', 'Sano'), ('ENFERMO', 'Enfermo'), ('TRATAMIENTO', 'En tratamiento')], max_length=20)),
                ('foto', models.ImageField(blank=True, upload_to='animales/')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('dosis', models.CharField(max_length=50)),
                ('veterinario', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganado.animal')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganado.vacuna')),
            ],
            options={
                'verbose_name_plural': 'Vacunaciones',
            },
        ),
    ]
